### PR TITLE
feat: add lua_ls types for the plugin's options

### PR DESCRIPTION
**Pull request by mikavilpas**
This way the users can know what options are available for the plugin.

### CODE REVIEW

**Comment by niuiic** [comment]
We have a document, and the types added only be used internally. In another word, users cannot see this.

**Comment by mikavilpas** [comment]
Sorry, maybe I wasn't very clear. The way I use this is by manually adding a type annotation to my own configuration.  That way I can get completions and documentation like this:

image

**Comment by niuiic** [comment]
You marked the type on the configuration, but most users would not do this.

**Comment by niuiic** [comment]
And some type annotations are wrong. For example, get_prefix does not have a parameter called self, we use `.`, not `:`, the first parameter is context

**Comment by mikavilpas** [comment]
Oops, nice catch. should be fixed now.

**Comment by niuiic** [comment]
Still some errors, no paramater named `self`. I have added the correct types, and close this pr.

By the way, health check is removed because ripgrep is an obvious dependency, in addition, the plugin allowing custom commands, ripgrep does not need to be in the PATH. Adding checks can be confusing for some users.

**Pull request closed without merging**
